import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";

import { Toaster } from "@/vendor/components/ui/sonner";
import { cn } from "@/vendor/lib/utils";

import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
    subsets: ["latin"],
    variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
    subsets: ["latin"],
    variable: "--font-geist-mono",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface Props {
    children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
    return (
        <html
            lang="en"
            className={cn(
                "h-full antialiased font-sans",
                inter.variable,
                geistSans.variable,
                geistMono.variable
            )}
        >
            <body className="flex min-h-full flex-col">
                {children}
                <Toaster richColors position="top-left" />
            </body>
        </html>
    );
}